apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /render/$1://$2$3$4
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - fullstackpro.dev
      secretName: fullstackpro-dev
  rules:
    - host: fullstackpro.dev
      http:
        paths:
          - path: /rendertron/render/(https|http):/(.+)(/?)(.*)
            backend:
              serviceName: rendertron-service
              servicePort: 3030
