apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /render/$1://$2$3$4
spec:
  rules:
    - http:
        paths:
          - path: /(https|http):/(.+)(/?)(.*)
            backend:
              serviceName: rendertron-service
              servicePort: 3030
