apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /render/https://test.europepmc.org/$1
spec:
  rules:
    - http:
        paths:
          - path: /(.*)
            backend:
              serviceName: rendertron-service
              servicePort: 3030
