apiVersion: apps/v1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: rendertron-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rendertron
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: rendertron
    spec:
      restartPolicy: Always
      volumes:
        - name: rendertron-storage
          persistentVolumeClaim:
            claimName: rendertron-pvc
      containers:
        - name: rendertron
          # Pulls the default Rendertron image from Docker Hub
          image: ygou/rendertron:2.0.1.2
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: rendertron-storage
              mountPath: /var/log/rendertron
              subPath: logs
          command: ['npx']
          args: ['rendertron', '>>', '/var/log/rendertron/$(hostname).log']
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "curl http://localhost:3000/render/https://europepmc.org/ContactUs | grep '<h1>Contact us</h1>'"
            failureThreshold: 2
            periodSeconds: 30
            timeoutSeconds: 15
            initialDelaySeconds: 70
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "curl http://localhost:3000/render/https://europepmc.org/ContactUs | grep '<h1>Contact us</h1>'"
            failureThreshold: 2
            periodSeconds: 30
            timeoutSeconds: 15
            initialDelaySeconds: 10
