apiVersion: apps/v1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: rendertron-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rendertron
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: rendertron
    spec:
      restartPolicy: Always
      containers:
        - name: rendertron
          # Pulls the default Rendertron image from Docker Hub
          image: ygou/rendertron:2.0.1.2
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /render/https://europepmc.org/ContactUs
              port: 3000
            failureThreshold: 2
            periodSeconds: 30
            timeoutSeconds: 15
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /render/https://europepmc.org/ContactUs
              port: 3000
            failureThreshold: 2
            periodSeconds: 30
            timeoutSeconds: 15
