apiVersion: apps/v1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: rendertron-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rendertron
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: rendertron
    spec:
      containers:
        - name: rendertron
          # Pulls the default Rendertron image from Docker Hub
          image: ygou/rendertron:2.0.1.2
          ports:
            - containerPort: 3000
