apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rendertron-pvc
  labels:
    app: rendertron-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
